// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj_26Qf9uN6obwrM2cDlp8tIDLjg9ztNU',
    appId: '1:163065620321:web:3000066a0d16c69a150720',
    messagingSenderId: '163065620321',
    projectId: 'chargemate-4ebe0',
    authDomain: 'chargemate-4ebe0.firebaseapp.com',
    storageBucket: 'chargemate-4ebe0.firebasestorage.app',
    measurementId: 'G-LC1MJCXCX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAXbcoWGmGCOAOmefXgoDnCIwrPNpDsD0',
    appId: '1:163065620321:android:300c33053644ac61150720',
    messagingSenderId: '163065620321',
    projectId: 'chargemate-4ebe0',
    storageBucket: 'chargemate-4ebe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNT_DAJvUT_gm0zN66vRZ7UxXcpqKB9ew',
    appId: '1:163065620321:ios:1c03aff1750366c4150720',
    messagingSenderId: '163065620321',
    projectId: 'chargemate-4ebe0',
    storageBucket: 'chargemate-4ebe0.firebasestorage.app',
    iosBundleId: 'com.example.chargemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNT_DAJvUT_gm0zN66vRZ7UxXcpqKB9ew',
    appId: '1:163065620321:ios:1c03aff1750366c4150720',
    messagingSenderId: '163065620321',
    projectId: 'chargemate-4ebe0',
    storageBucket: 'chargemate-4ebe0.firebasestorage.app',
    iosBundleId: 'com.example.chargemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj_26Qf9uN6obwrM2cDlp8tIDLjg9ztNU',
    appId: '1:163065620321:web:f9bf50fe82c2cad0150720',
    messagingSenderId: '163065620321',
    projectId: 'chargemate-4ebe0',
    authDomain: 'chargemate-4ebe0.firebaseapp.com',
    storageBucket: 'chargemate-4ebe0.firebasestorage.app',
    measurementId: 'G-NGTZ5BC5GZ',
  );
}
